'use strict';
const fs = require('fs');
const path = require('path');

function vietnameseSlugify(str) {
  return str
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/đ/g, 'd').replace(/Đ/g, 'D')
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/[\s_]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

const data = JSON.parse(fs.readFileSync(path.resolve(__dirname, '../scratch/food_image_scan_result.json'), 'utf-8'));
const items = data.filter(i => i.status === 'REPLACE' || i.status === 'MISSING');

const dict = {
  "Ức gà (Thô)": "Raw chicken breast",
  "Thịt bò thăn (Thô)": "Raw beef tenderloin",
  "Cá hồi tươi (Thô)": "Raw fresh salmon",
  "Cá rô phi (Thô)": "Raw tilapia",
  "Tôm tươi (Thô)": "Raw fresh shrimp",
  "Đậu phụ (Thô)": "Raw tofu",
  "Sữa chua Hy Lạp (Thô)": "Greek yogurt",
  "Thịt đùi gà (Bỏ da)": "Raw skinless chicken thigh",
  "Thịt lợn thăn (Nạc)": "Raw lean pork tenderloin",
  "Bắp bò (Nạc)": "Raw lean beef shank",
  "Cá ngừ đại dương": "Raw ocean tuna",
  "Mực ống tươi": "Raw fresh squid",
  "Bạch tuộc": "Raw octopus",
  "Lòng đỏ trứng (Thô)": "Raw egg yolk",
  "Đậu nành (Hạt khô)": "Dried soybeans",
  "Đậu Hà Lan": "Green peas",
  "Phô mai tươi (Cottage Cheese)": "Cottage cheese",
  "Hàu tươi": "Raw fresh oyster",
  "Cua biển": "Raw mud crab",
  "Cá basa": "Raw basa fish",
  "Hạnh nhân sữa (Milk Almond)": "Almond milk",
  "Tempeh (Tương nén)": "Raw tempeh",
  "Lươn (Thô)": "Raw eel",
  "Ếch (Thô)": "Raw frog meat",
  "Sò huyết": "Raw blood cockle",
  "Ngao (Nghêu)": "Raw clam",
  "Cá lóc (Thô)": "Raw snakehead fish",
  "Cá diêu hồng (Thô)": "Raw red tilapia",
  "Hến": "Raw baby clams",
  "Đậu hũ non (Thô)": "Raw silken tofu",
  "Trứng vịt (Thô)": "Raw duck egg",
  "Sữa đậu nành không đường": "Unsweetened soy milk",
  "Cơm trắng (Thô/Chín)": "White rice",
  "Yến mạch khô (Thô)": "Dry rolled oats",
  "Gạo lứt (Thô)": "Raw brown rice",
  "Khoai lang (Thô)": "Raw sweet potato",
  "Hạt Quinoa (Thô)": "Raw quinoa",
  "Ngô ngọt (Bắp)": "Sweet corn",
  "Bí đỏ (Bí ngô)": "Raw pumpkin",
  "Đậu đỏ (Hạt khô)": "Dried red beans",
  "Đậu xanh (Hạt khô)": "Dried mung beans",
  "Sắn (Khoai mì)": "Raw cassava",
  "Bánh mì nguyên cám": "Whole wheat bread",
  "Bánh mì đen": "Dark rye bread",
  "Bánh thuyền gạo lứt": "Brown rice boat cake",
  "Bún tươi (Thô)": "Fresh rice vermicelli",
  "Bánh phở tươi": "Fresh pho noodles",
  "Miến dong (Thô)": "Dry arrowroot vermicelli",
  "Gạo nếp (Thô)": "Raw glutinous rice",
  "Bột sắn dây": "Cassava flour",
  "Bông cải xanh (Thô)": "Raw broccoli",
  "Măng tây": "Raw asparagus",
  "Rau cải chíp": "Raw bok choy",
  "Rau muống": "Raw water spinach",
  "Nấm kim châm": "Raw enoki mushrooms",
  "Nấm đùi gà": "Raw king oyster mushrooms",
  "Củ cải trắng": "Raw white radish",
  "Dưa chuột": "Raw cucumber",
  "Cà chua": "Raw tomato",
  "Rau ngót": "Raw katuk leaves",
  "Rau dền": "Raw amaranth leaves",
  "Rau mồng tơi": "Raw malabar spinach",
  "Cải bẹ xanh": "Raw mustard greens",
  "Cải thảo": "Raw napa cabbage",
  "Mướp đắng (Khổ qua)": "Raw bitter melon",
  "Bầu": "Raw bottle gourd",
  "Bí xanh (Bí đao)": "Raw winter melon",
  "Giá đỗ": "Raw bean sprouts",
  "Su hào": "Raw kohlrabi",
  "Củ dền": "Raw beetroot",
  "Cà rốt": "Raw carrot",
  "Bắp cải (Thô)": "Raw cabbage",
  "Đậu cô ve (Thô)": "Raw green beans",
  "Đậu bắp (Thô)": "Raw okra",
  "Nấm rơm (Thô)": "Raw straw mushrooms",
  "Súp lơ trắng (Thô)": "Raw cauliflower",
  "Mộc nhĩ (Nấm mèo khô)": "Dried wood ear mushrooms",
  "Cà tím (Thô)": "Raw eggplant",
  "Chuối (Thô)": "Fresh banana",
  "Táo đỏ (Thô)": "Fresh apple",
  "Quả Việt quất": "Fresh blueberries",
  "Quả Dâu tây": "Fresh strawberries",
  "Đu đủ (Chín)": "Ripe papaya",
  "Xoài (Chín)": "Ripe mango",
  "Dưa hấu (Thô)": "Fresh watermelon",
  "Thanh long (Thô)": "Fresh dragon fruit",
  "Bưởi (Thô)": "Fresh pomelo",
  "Ổi (Thô)": "Fresh guava",
  "Nho tươi (Thô)": "Fresh grapes",
  "Quả Bơ (Thô)": "Fresh avocado",
  "Hạt Hạnh nhân (Thô)": "Raw almonds",
  "Hạt Chia (Thô)": "Raw chia seeds",
  "Dầu Olive (Thô)": "Olive oil",
  "Hạt Óc chó": "Raw walnuts",
  "Hạt Điều": "Raw cashews",
  "Hạt Bí": "Raw pumpkin seeds",
  "Bơ đậu phộng (Nguyên chất)": "Pure peanut butter",
  "Đậu phộng (Lạc thô)": "Raw peanuts",
  "Mỡ heo (Thô)": "Raw pork fat",
  "Hạt Macca": "Raw macadamia nuts",
  "Quả Ô liu": "Olives",
  "Thịt vịt (Nạc)": "Raw duck meat",
  "Cá thu (Thô)": "Raw mackerel",
  "Cá chép (Thô)": "Raw carp",
  "Thịt thỏ (Thô)": "Raw rabbit meat",
  "Tôm sú (Thô)": "Raw tiger prawn",
  "Cá trích (Thô)": "Raw herring",
  "Sữa tươi không đường": "Unsweetened fresh milk",
  "Khoai tây (Thô)": "Raw potato",
  "Khoai môn (Thô)": "Raw taro",
  "Bún khô (Thô)": "Dried rice vermicelli",
  "Mì sợi khô (Thô)": "Dried noodles",
  "Bánh tráng (Thô)": "Rice paper",
  "Rau xà lách": "Raw lettuce",
  "Cải xoăn (Kale)": "Raw kale",
  "Ớt chuông": "Raw bell pepper",
  "Rau chân vịt (Spinach)": "Raw spinach",
  "Nấm hương khô": "Dried shiitake mushrooms",
  "Cam (Thô)": "Fresh orange",
  "Quýt (Thô)": "Fresh mandarin",
  "Kiwi (Thô)": "Fresh kiwi",
  "Lê (Thô)": "Fresh pear",
  "Mận (Thô)": "Fresh plum",
  "Dứa (Thơm)": "Fresh pineapple",
  "Măng cụt (Thô)": "Fresh mangosteen",
  "Chôm chôm (Thô)": "Fresh rambutan",
  "Hạt Hướng dương": "Sunflower seeds",
  "Hạt Lanh (Flaxseed)": "Flaxseeds",
  "Mít (Thô)": "Fresh jackfruit",
  "Sầu riêng (Thô)": "Fresh durian",
  "Nhãn (Thô)": "Fresh longan",
  "Vải (Thô)": "Fresh lychee",
  "Dưa lưới (Thô)": "Fresh cantaloupe",
  "Dầu đậu nành (Thô)": "Soybean oil",
  "Dầu hướng dương (Thô)": "Sunflower oil",
  "Bơ thực vật (Margarine)": "Margarine",
  "Nước cốt dừa": "Coconut milk",
  "Salad Ức gà áp chảo": "Pan-seared chicken breast salad",
  "Cơm gạo lứt thịt bò": "Brown rice with beef",
  "Bánh mì ngũ cốc trứng": "Multigrain bread with egg",
  "Phở Gà": "Chicken pho",
  "Bún Bò Huế": "Spicy beef noodle soup",
  "Cơm Tấm Sườn": "Vietnamese broken rice with grilled pork chop",
  "Bún Chả": "Vietnamese grilled pork with vermicelli",
  "Bún Đậu Mắm Tôm": "Vermicelli with fried tofu and shrimp paste",
  "Bánh Mì Pate Xá Xíu": "Vietnamese banh mi with pate and char siu",
  "Miến Lươn": "Glass noodle soup with eel",
  "Mì Tôm Trứng": "Instant noodles with egg",
  "Xôi Xéo": "Sticky rice with mung bean and fried shallots",
  "Gỏi Cuốn Tôm Thịt": "Vietnamese fresh spring rolls with pork and shrimp",
  "Cháo Lòng": "Pork offal congee",
  "Bún Riêu Cua": "Crab paste vermicelli soup",
  "Cơm Rang Dưa Bò": "Fried rice with beef and pickled mustard greens",
  "Bánh Cuốn Thịt": "Steamed rice rolls with minced pork",
  "Nộm Bò Khô": "Dried beef salad",
  "Bún Mọc": "Porkball vermicelli soup",
  "Miến Gà": "Glass noodle soup with chicken",
  "Cháo Yến Mạch Sữa Tươi": "Oatmeal congee with fresh milk",
  "Bánh Cuốn Thanh Trì": "Thanh Tri steamed rice rolls",
  "Bánh Mì Trứng Ốp La": "Banh mi with sunny-side up eggs",
  "Ức Gà Áp Chảo Sốt Chanh Dây": "Pan-seared chicken breast with passion fruit sauce",
  "Cá Hồi Nướng Măng Tây": "Grilled salmon with asparagus",
  "Salad Bơ Tôm": "Avocado and shrimp salad",
  "Cơm Gà Hải Nam": "Hainanese chicken rice",
  "Phở Bò Tái Lăn": "Pho with stir-fried beef",
  "Bún Chả Cá": "Fish cake vermicelli soup",
  "Canh Chua Cá Lóc": "Sour soup with snakehead fish",
  "Thịt Kho Trứng": "Caramelized pork and eggs",
  "Đậu Hũ Nhồi Thịt Sốt Cà": "Stuffed tofu with tomato sauce",
  "Gà Xào Sả Ớt": "Stir-fried chicken with lemongrass and chili",
  "Bò Xào Cần Tây": "Stir-fried beef with celery",
  "Canh Khổ Qua Nhồi Thịt": "Stuffed bitter melon soup",
  "Rau Muống Xào Tỏi": "Stir-fried water spinach with garlic",
  "Trứng Đúc Thịt": "Vietnamese steamed egg meatloaf",
  "Đùi Gà Rô Ti": "Vietnamese roasted chicken thigh",
  "Bowl Cơm Lứt Cá Hồi Bơ": "Brown rice bowl with salmon and avocado",
  "Salad Quinoa Rau Củ": "Quinoa vegetable salad",
  "Ức Gà Nướng Mật Ong": "Honey grilled chicken breast",
  "Cá Ngừ Áp Chảo Salad": "Seared tuna salad",
  "Súp Bí Đỏ Kem Tươi": "Creamy pumpkin soup",
  "Cơm Lứt Gà Xé Rau Củ": "Brown rice with shredded chicken and vegetables",
  "Bún Gạo Lứt Tôm Hấp": "Brown rice vermicelli with steamed shrimp",
  "Salad Trứng Luộc Rau Mầm": "Boiled egg and microgreens salad",
  "Tôm Hấp Sả": "Steamed shrimp with lemongrass",
  "Cá Diêu Hồng Hấp Hành": "Steamed red tilapia with scallions",
  "Gà Luộc Lá Chanh": "Boiled chicken with lime leaves",
  "Bò Cuốn Lá Lốt Nướng": "Grilled beef wrapped in lolot leaves",
  "Đậu Hũ Sốt Nấm": "Tofu with mushroom sauce",
  "Cải Bó Xôi Xào Tỏi": "Stir-fried spinach with garlic",
  "Bông Cải Xanh Luộc": "Boiled broccoli",
  "Măng Tây Xào Tôm": "Stir-fried asparagus with shrimp",
  "Canh Rau Ngót Thịt Bằm": "Katuk leaves soup with minced pork",
  "Canh Bí Đao Tôm Khô": "Winter melon soup with dried shrimp",
  "Cháo Gà Gạo Lứt": "Brown rice chicken congee",
  "Yến Mạch Trái Cây Hạt": "Oatmeal with fruits and nuts",
  "Cơm Cuộn Rong Biển (Kimbap)": "Kimbap",
  "Bò Bít Tết Rau Nướng": "Beefsteak with grilled vegetables",
  "Cá Basa Hấp Gừng": "Steamed basa fish with ginger",
  "Salad Caesar Gà Nướng": "Grilled chicken Caesar salad",
  "Wrap Gà Rau Củ": "Chicken and vegetable wrap",
  "Cơm Chiên Trứng Rau Củ": "Egg and vegetable fried rice",
  "Phở Chay Rau Nấm": "Vegetarian pho with mushrooms",
  "Bún Chả Giò Chay": "Vegetarian spring rolls with vermicelli",
  "Cá Lóc Nướng Trui": "Grilled snakehead fish",
  "Thịt Heo Luộc Chấm Mắm": "Boiled pork with fish sauce",
  "Cơm Gạo Lứt Cá Kho": "Brown rice with caramelized fish",
  "Bowl Poke Cá Hồi": "Salmon poke bowl",
  "Bún Bò Xào Rau Củ": "Stir-fried beef and vegetables with vermicelli",
  "Súp Gà Ngô Non": "Chicken and sweet corn soup",
  "Súp Hành Tây Phô Mai": "French onion soup with cheese",
  "Trứng Hấp Nấm": "Steamed egg with mushrooms",
  "Sandwich Ức Gà Rau Xanh": "Chicken breast sandwich with greens",
  "Cá Hấp Xì Dầu Gừng": "Steamed fish with soy sauce and ginger",
  "Gà Nướng Ngũ Vị": "Five-spice grilled chicken",
  "Nấm Đùi Gà Xào Bơ Tỏi": "Stir-fried king oyster mushrooms with garlic butter",
  "Mì Ý Sốt Cà Chua Thịt Bò": "Spaghetti bolognese",
  "Cơm Gạo Lứt Tôm Rang": "Brown rice with roasted shrimp",
  "Canh Cải Thảo Nấu Tôm": "Napa cabbage soup with shrimp",
  "Đậu Hũ Chiên Sả Ớt": "Fried tofu with lemongrass and chili",
  "Gỏi Bưởi Tôm Thịt": "Pomelo salad with shrimp and pork",
  "Mì Udon Hải Sản": "Seafood udon",
  "Bún Thịt Nướng Chả Giò": "Grilled pork and spring rolls with vermicelli",
  "Cơm Trộn Hàn Quốc (Bibimbap)": "Bibimbap",
  "Gà Hấp Muối Sả": "Steamed chicken with salt and lemongrass",
  "Canh Bầu Nấu Tôm": "Bottle gourd soup with shrimp",
  "Bắp Cải Cuốn Thịt Hấp": "Steamed cabbage rolls with pork",
  "Cá Rô Phi Chiên Giòn": "Crispy fried tilapia",
  "Salad Bò Thái Lan": "Thai beef salad",
  "Cơm Nấm Hấp Lá Sen": "Steamed rice with mushrooms in lotus leaf",
  "Mì Soba Lạnh Rau Củ": "Cold soba noodles with vegetables",
  "Tôm Nướng Muối Ớt": "Grilled shrimp with chili salt",
  "Canh Mồng Tơi Mướp": "Malabar spinach and luffa soup",
  "Cơm Chiên Kimchi": "Kimchi fried rice",
  "Thịt Bò Xào Ớt Chuông": "Stir-fried beef with bell peppers",
  "Cá Thu Nướng Nghệ": "Grilled mackerel with turmeric",
  "Soup Rau Củ Detox": "Detox vegetable soup",
  "Ức Vịt Áp Chảo Sốt Cam": "Pan-seared duck breast with orange sauce",
  "Cơm Lứt Đậu Hũ Rong Biển": "Brown rice with tofu and seaweed",
  "Bún Măng Gà": "Chicken and bamboo shoot vermicelli soup",
  "Cá Chẽm Hấp Hồng Kông": "Hong Kong style steamed sea bass",
  "Bánh Pancake Chuối Yến Mạch": "Banana oat pancakes",
  "Bowl Açaí Trái Cây": "Acai fruit bowl",
  "Rau Củ Hấp Chấm Mắm Nêm": "Steamed vegetables with fermented anchovy sauce",
  "Thịt Bò Hầm Khoai Tây Cà Rốt": "Beef stew with potatoes and carrots",
  "Tôm Xào Bông Cải Xanh": "Stir-fried shrimp with broccoli",
  "Cháo Cá Lóc Rau Đắng": "Snakehead fish congee with bitter herbs",
  "Bún Nước Lèo Sóc Trăng": "Soc Trang style noodle soup",
  "Sườn Non Om Sấu": "Braised pork ribs with dracontomelon",
  "Gà Xào Hạt Điều": "Stir-fried chicken with cashews",
  "Canh Su Hào Nấu Sườn": "Kohlrabi soup with pork ribs",
  "Chả Cá Lã Vọng": "La Vong grilled fish",
  "Mì Quảng": "Mi Quang noodle",
  "Bún Cá Châu Đốc": "Chau Doc fish noodle soup",
  "Hủ Tiếu Nam Vang": "Nam Vang noodle soup",
  "Cơm Chiên Dương Châu": "Yangzhou fried rice",
  "Gỏi Cuốn Chay": "Vegetarian fresh spring rolls",
  "Salad Kale Hạt Quinoa": "Kale quinoa salad",
  "Bánh Mì Thịt Nguội": "Banh mi with cold cuts",
  "Bánh Mì Ốp La": "Banh mi with fried eggs",
  "Bánh Mì Chảo (Hết thứ)": "Vietnamese sizzling banh mi pan",
  "Xôi Gà": "Sticky rice with chicken",
  "Xôi Đậu Xanh": "Sticky rice with mung bean",
  "Xôi Lạc": "Sticky rice with peanuts",
  "Xôi Ngô Mỡ Hành": "Sticky rice with corn and scallion oil",
  "Cháo Đậu Xanh": "Mung bean congee",
  "Cháo Thịt Bằm": "Minced pork congee",
  "Bánh Giò": "Pyramid meat dumpling",
  "Bánh Bao Thịt": "Pork bun",
  "Bánh Bao Chay": "Vegetarian steamed bun",
  "Bánh Ướt Chả Lụa": "Steamed rice paper with Vietnamese sausage",
  "Hủ Tiếu Khô Thịt": "Dry noodle with pork",
  "Mì Khô Xá Xíu": "Dry egg noodles with char siu",
  "Bún Bò Nam Bộ": "Southern style beef vermicelli",
  "Cơm Sườn Cải": "Rice with grilled pork chop and mustard greens",
  "Cơm Gà Chiên Nước Mắm": "Rice with fish sauce fried chicken",
  "Cơm Bò Kho": "Rice with beef stew",
  "Cơm Canh Chua Cá": "Rice with sour fish soup",
  "Cơm Thịt Kho Tiêu": "Rice with caramelized pork with pepper",
  "Cơm Cá Kho Tộ": "Rice with braised fish in clay pot",
  "Cơm Trắng + Rau Xào": "White rice with stir-fried vegetables",
  "Cơm Đùi Gà Nướng": "Rice with grilled chicken thigh",
  "Cơm Chả Trứng": "Rice with Vietnamese steamed egg meatloaf",
  "Bún Bò Xào Sả": "Vermicelli with lemongrass beef",
  "Canh Chua Tôm": "Sour soup with shrimp",
  "Đậu Phụ Sốt Thịt Bằm": "Tofu with minced pork sauce",
  "Rau Cải Luộc Chấm Mắm": "Boiled mustard greens with fish sauce",
  "Bánh Tráng Nướng Phomai": "Vietnamese grilled rice paper with cheese",
  "Bánh Tráng Trộn": "Vietnamese mixed rice paper salad",
  "Khoai Lang Lắc Phô Mai": "Cheese shaken sweet potatoes",
  "Ngô Luộc": "Boiled corn",
  "Khoai Lang Luộc": "Boiled sweet potato",
  "Chuối Lán": "Fried banana",
  "Ổi Xanh Chấm Muối Ớt": "Green guava with chili salt",
  "Chè Đậu Xanh": "Mung bean sweet soup",
  "Chè Ba Màu": "Three-color sweet dessert",
  "Chè Bưởi Sương Sáo": "Pomelo and grass jelly sweet soup",
  "Sữa Chua Nếp Cẩm": "Yogurt with black glutinous rice",
  "Hạt Điều Rang Muối": "Salt roasted cashews",
  "Trái Cây Dầm": "Mixed fruit dessert",
  "Bánh Flan": "Flan cake",
  "Sữa Chua Hoa Quả": "Fruit yogurt",
  "Bún Thái Hải Sản": "Thai seafood vermicelli",
  "Bánh Xèo Tôm Thịt": "Vietnamese sizzling pancake with shrimp and pork",
  "Mì Quảng Gà": "Mi Quang with chicken",
  "Cao Lầu Hội An": "Hoi An Cao Lau noodles",
  "Bún Kèn Phú Quốc": "Phu Quoc Ken noodles",
  "Cơm Niêu Sài Gòn": "Saigon clay pot rice",
  "Lẩu Mắm": "Fermented fish hot pot",
  "Lẩu Thái Hải Sản": "Thai seafood hot pot",
  "Lẩu Gà Lá Giang": "Chicken hot pot with river-creeper leaves",
  "Thịt Nướng BBQ Mỡ Hành": "BBQ meat with scallion oil",
  "Gà Nướng Muối Ớt": "Chili salt grilled chicken",
  "Sườn Nướng Mật Ong": "Honey grilled pork ribs",
  "Cơm Chay Thập Cẩm": "Mixed vegetarian rice",
  "Bún Chay Sốt Nấm": "Vegetarian vermicelli with mushroom sauce",
  "Bánh Mì Chay": "Vegetarian banh mi",
  "Đậu Hũ Kho Sả Ớt": "Braised tofu with lemongrass and chili",
  "Canh Rau Củ Chay": "Vegetarian vegetable soup",
  "Nấm Xào Rau Củ": "Stir-fried mushrooms and vegetables",
  "Cá Viên Chiên": "Fried fish balls",
  "Gà Rán (KFC-style)": "Fried chicken",
  "Pizza Phô Mai": "Cheese pizza",
  "Hamburger Bò Phô Mai": "Beef cheeseburger",
  "Nước Ép Cam Tươi": "Fresh orange juice",
  "Nước Ép Dưa Hấu": "Watermelon juice",
  "Nước Ép Táo": "Apple juice",
  "Nước Ép Cà Rốt": "Carrot juice",
  "Nước Ép Dứa": "Pineapple juice",
  "Nước Ép Ổi": "Guava juice",
  "Nước Ép Bưởi": "Pomelo juice",
  "Nước Ép Rau Má": "Pennywort juice",
  "Nước Ép Cần Tây": "Celery juice",
  "Nước Ép Lựu": "Pomegranate juice",
  "Nước Mía": "Sugarcane juice",
  "Sinh Tố Bơ": "Avocado smoothie",
  "Sinh Tố Chuối Sữa": "Banana milk smoothie",
  "Sinh Tố Xoài": "Mango smoothie",
  "Sinh Tố Dâu Tây": "Strawberry smoothie",
  "Smoothie Protein Chuối Yến Mạch": "Banana oat protein smoothie",
  "Smoothie Bowl Việt Quất": "Blueberry smoothie bowl",
  "Sinh Tố Thanh Long Sữa Chua": "Dragon fruit yogurt smoothie",
  "Sữa Milo Nóng": "Hot Milo",
  "Sữa Milo Đá": "Iced Milo",
  "Sữa Đậu Nành": "Soy milk",
  "Sữa Tươi Có Đường": "Sweetened fresh milk",
  "Sữa Chua Uống": "Drinking yogurt",
  "Sữa Hạt Óc Chó": "Walnut milk",
  "Sữa Yến Mạch (Oat Milk)": "Oat milk",
  "Trà Xanh Không Đường": "Unsweetened green tea",
  "Trà Đào Cam Sả": "Peach orange lemongrass tea",
  "Trà Sữa Trân Châu": "Bubble milk tea",
  "Trà Chanh Mật Ong": "Honey lemon tea",
  "Trà Gừng Mật Ong": "Honey ginger tea",
  "Cà Phê Đen Không Đường": "Black coffee no sugar",
  "Cà Phê Sữa Đá": "Vietnamese iced milk coffee",
  "Cappuccino": "Cappuccino",
  "Latte": "Latte",
  "Nước Dừa Tươi": "Fresh coconut water",
  "Nước Chanh Muối": "Salted lemonade",
  "Nước Sâm Bổ Lượng": "Ching bo leung sweet soup",
  "Nước Rau Má Đậu Xanh": "Pennywort juice with mung bean",
  "Trà Đá": "Iced tea"
};

const result = [];
const engToIds = {};

items.forEach(item => {
  let eng = dict[item.name];
  if (!eng) {
    eng = vietnameseSlugify(item.name).replace(/-/g, ' ');
  }
  
  const key = eng.toLowerCase() + '-' + item.foodType; // Dedup based on english name AND foodType
  if (!engToIds[key]) {
    engToIds[key] = [];
  }
  engToIds[key].push(item.id);

  result.push({
    id: item.id,
    vietnamese: item.name,
    english: eng,
    foodType: item.foodType,
    category: item.category,
    filename: vietnameseSlugify(item.name) + '.webp',
    shared_with_ids: [] // computed below
  });
});

result.forEach(r => {
  const key = r.english.toLowerCase() + '-' + r.foodType;
  const allIds = engToIds[key];
  r.shared_with_ids = allIds.filter(id => id !== r.id);
  if (r.shared_with_ids.length > 0) {
    // Only the first one in the list handles generation. Others just reference.
    if (r.id !== allIds[0]) {
        r._note = `Dùng chung ảnh với ID ${allIds[0]} — chỉ generate 1 lần`;
    }
  }
});

fs.writeFileSync(path.resolve(__dirname, '../scratch/food_name_mapping.json'), JSON.stringify(result, null, 2), 'utf-8');
console.log('Mapping generated successfully with', result.length, 'items.');
